FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Redis URL por defecto y SMTP dummy
ENV REDIS_URL=redis://redis:6379/0 \
    SMTP_TLS=true \
    PRINT_LOG_DB=/app/logs.db

EXPOSE 4005

CMD ["uvicorn", "notifications.main:app", "--host", "0.0.0.0", "--port", "4005"]
